version: '3.8'

services:
  twitter-postgres:
    image: postgres:15.4-alpine3.18
    environment:
      POSTGRES_DB: tweet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"